# Dockerfile for empathy-query API
FROM python:3.11-slim
WORKDIR /app
COPY integration/api_server.py .
RUN pip install flask
CMD ["python", "api_server.py"]

# docker-compose.yml
version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./integration
    ports:
      - "5000:5000"
    volumes:
      - ./integration:/app

  haskell:
    build:
      context: ./haskell
    command: ["./main"]
  
  prolog:
    build:
      context: ./prolog
    command: ["swipl", "-s", "logic.pl"]
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: empathy
      POSTGRES_DB: harmonia
    ports:
      - "5432:5432"
