name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: nexus
          POSTGRES_PASSWORD: empathy
          POSTGRES_DB: harmonia
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests pytest

     # - name: Verify pytest is available
     #   run: |
     #     pytest --version

      #- name: Run Python tests
      #  run: |
      #  pytest integration/tests/

      - name: Build Docker containers
        run: |
          docker compose -f docker-compose.yml build

      # Optional future steps:
      # - name: Frontend lint/build
      # - name: Compile Haskell logic
      # - name: Run Prolog tests
      # - name: Accessibility checks
      # - name: Code coverage upload

      - name: Confirm PostgreSQL Service
        run: |
          psql -h localhost -U nexus -d harmonia -c "SELECT 1;"
        env:
          PGPASSWORD: empathy
