name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: nexus
          POSTGRES_PASSWORD: empathy
          POSTGRES_DB: harmonia
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
        python -m pip install --upgrade pip
        pip install flask requests pytest


      - name: Verify pytest is available
        run: |
          pytest --version

      - name: Wait for PostgreSQL
        run: |
          for i in {1..15}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Confirm PostgreSQL Service
        run: |
          psql -h localhost -U nexus -d harmonia -c "SELECT 1;"
        env:
          PGPASSWORD: empathy

      - name: Run Python tests
        run: |
          pytest integration/tests/test_api_server.py integration/tests/test_health_check.py --tb=short -v

      # Optional future steps:
      - name: Frontend lint/build
        run: echo "Frontend build placeholder"

      - name: Compile Haskell logic
        run: echo "Haskell compile placeholder"

      - name: Run Prolog tests
        run: echo "Prolog tests placeholder"

      - name: Accessibility checks
        run: echo "Accessibility checks placeholder"

      - name: Code coverage upload
        run: echo "Code coverage upload placeholder"
